# k8s deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-9
  labels:
    app: nginx-app-9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app-9
  template:
    metadata:
      labels:
        app: nginx-app-9
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "10Mi"
            cpu: "100m"
          limits:
            memory: "10Mi"
            cpu: "100m"