apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app3
  labels:
    app: nginx-app3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app3
  template:
    metadata:
      labels:
        app: nginx-app3
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "10Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
