# k8s Application CRD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-app-2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: my-apps/app-2
    repoURL: https://github.com/thanawit-k/ArgoCD-Ops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true